---
# tasks/main.yml

- name: Install httpd package
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Start and enable httpd service
  ansible.builtin.systemd:
    name: httpd
    state: started
    enabled: true

- name: Add index
  copy:
    src: /etc/ansible/index.html
    dest: /var/www/html/index.html

- name: Ensure the firewall allows HTTP traffic
  ansible.builtin.firewalld:
    service: http
    permanent: true
    state: enabled
  notify: restart_firewalld

