---
# This playbook deploys a simple web application
- name: Install and Configure Apache HTTP Server
  hosts: webservers
  become: true

  tasks:
    - name: Install httpd package
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start and enable httpd service
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true

    - name: Ensure the firewall allows HTTP traffic
      ansible.builtin.firewalld:
        service: http
        permanent: true
        state: enabled
      notify: restart_firewalld

  handlers:
    - name: restart_firewalld
      ansible.builtin.service:
        name: firewalld
        state: restarted

