---
- name: Add users to testservers group
  hosts: testservers
  become: yes
  tasks:
    - name: Ensure users are created
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - test1
        - test2
        - test3
