---
- hosts: node2
  vars:
    httpd_server_root: "/etc/httpd"
    httpd_listen_port: 80
    httpd_server_admin: "admin@example.com"
    httpd_server_name: "www.example.com"
    httpd_document_root: "/var/www/html"
    httpd_directory_index: "index.html"
    httpd_error_log: "/var/log/httpd/error_log"
    httpd_custom_log: "/var/log/httpd/access_log"
    httpd_modules:
      - "auth_basic_module modules/mod_auth_basic.so"
      - "auth_digest_module modules/mod_auth_digest.so"
  tasks:
    - name: Configure Apache
      ansible.builtin.template:
        src: httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
      become: yes
